   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: hello-app
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: hello
     template:
       metadata:
         labels:
           app: hello
       spec:
         containers:
         - name: hello
           image: nginx:latest
           ports:
           - containerPort: 80